# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for pip
  - package-ecosystem: "pip"
    # Look for `requirements`in directory
    directory: "/"
    # Check the pypi for updates
    labels:
      - "pip"
      - "dependencies"
    commit-message:
      # Prefix all commit messages with "pip"
      prefix: "pip"
      include: "scope"
    schedule:
      interval: "cron"
      # Run on the 2nd Saturday of each month at 04:00
      cronjob: "0 4 8-14 * 6"
      timezone: "America/New_York"
    # schedule:
    #   cron: '0 0 5 ? 1/1 SAT#1 *'
  # packages:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "github actions"
      - "dependencies"
    commit-message:
      # Prefix all commit messages with "github-actions"
      prefix: "github-actions"
      include: "scope"
    schedule:
      interval: "cron"
      # Run on the 2nd Saturday of each month at 04:00
      cronjob: "0 4 8-14 * 6"
      timezone: "America/New_York"